# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=35, null=True)),
                ('city', models.CharField(max_length=35, null=True)),
                ('pincode', models.CharField(max_length=7, null=True)),
                ('pin_status', models.CharField(default='1', max_length=2)),
            ],
        ),
    ]
