# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_auto_20200122_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediav2',
            name='mediaType',
            field=models.CharField(default='image', max_length=30),
        ),
    ]
