# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_genericpincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpincode',
            name='country',
            field=models.CharField(default='India', max_length=35, null=True),
        ),
    ]
