# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-22 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_auto_20200122_1317'),
        ('POS', '0003_genericpincode_country'),
    ]

    operations = [
    ]
