# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_merge_20200122_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='POS.GenericProductV2')),
                ('products', models.ManyToManyField(blank=True, related_name='filters', to='POS.ProductV2')),
            ],
        ),
    ]
