# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
