# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_auto_20200123_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantv2',
            name='gstType',
            field=models.CharField(choices=[('gst_included', 'gst_included'), ('gst_extra', 'gst_extra'), ('gst_not_applicable', 'gst_not_applicable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantv2',
            name='unitType',
            field=models.CharField(choices=[('Ton', 'Ton'), ('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Litre', 'Litre'), ('Millilitre', 'Millilitre'), ('Quantity', 'Quantity'), ('Size', 'Size'), ('Size and Color', 'Size and Color'), ('Color', 'Color'), ('Quantity and Color', 'Quantity and Color')], max_length=50, null=True),
        ),
    ]
