# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-24 12:50
from __future__ import unicode_literals

import POS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0009_auto_20200124_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logoinverted',
            field=models.FileField(null=True, upload_to=POS.models.getgstincert),
        ),
    ]
