# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0010_store_logoinverted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='filters', to='POS.ProductVariantV2'),
        ),
    ]
