# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-25 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0012_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productCart', to='POS.ProductV2'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productVariant',
        ),
        migrations.AddField(
            model_name='cart',
            name='productVariant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productVariantCart', to='POS.ProductVariantV2'),
        ),
    ]
