# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-27 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0016_auto_20200126_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesv2',
            name='options',
            field=models.CharField(choices=[('offers', 'offers'), ('footer', 'footer'), ('general', 'general')], default='offers', max_length=25),
        ),
    ]
