# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 11:28
from __future__ import unicode_literals

import POS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0017_auto_20200127_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='customisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizedDetails', models.CharField(max_length=2000, null=True)),
                ('customizedFile', models.FileField(null=True, upload_to=POS.models.getgstincert)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customizedDetails',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customizedFile',
        ),
        migrations.AddField(
            model_name='cart',
            name='customisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customisation', to='POS.customisation'),
        ),
    ]
