# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-27 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0018_auto_20200127_1128'),
        ('POS', '0017_pagesv2_options'),
    ]

    operations = [
    ]
