# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-28 14:13
from __future__ import unicode_literals

import POS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0019_merge_20200127_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customisation',
        ),
        migrations.AddField(
            model_name='cart',
            name='customDetails',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='customFile',
            field=models.FileField(null=True, upload_to=POS.models.getgstincert),
        ),
        migrations.DeleteModel(
            name='customisation',
        ),
    ]
