# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0022_address_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='billingCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='billingCountry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='billingLandMark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='billingPincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='billingState',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='billingStreet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='sameAsShipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(max_length=200, null=True),
        ),
    ]
