# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0023_auto_20200128_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
