# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0024_auto_20200128_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('totalAmount', models.FloatField(default=0)),
                ('paymentMode', models.CharField(choices=[('COD', 'COD'), ('card', 'card'), ('cash', 'cash'), ('discussion', 'discussion')], max_length=10)),
                ('landMark', models.CharField(blank=True, max_length=100, null=True)),
                ('billingLandMark', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=300, null=True)),
                ('billingStreet', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('billingCity', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('billingState', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('billingPincode', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('billingCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('mobileNo', models.CharField(blank=True, max_length=15, null=True)),
                ('shippingCharges', models.FloatField(default=0)),
                ('orderBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderQtyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('orderBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedUser', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderProduct', to='POS.ProductV2')),
                ('productVariant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderVariant', to='POS.ProductVariantV2')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderQtyMap',
            field=models.ManyToManyField(blank=True, related_name='order', to='POS.OrderQtyMap'),
        ),
    ]
