# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0026_auto_20200128_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqtymap',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
