# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0027_orderqtymap_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMode',
            field=models.CharField(choices=[('COD', 'COD'), ('card', 'card'), ('cash', 'cash'), ('discussion', 'discussion')], default='COD', max_length=10),
        ),
    ]
