# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0028_auto_20200128_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sameAsShipping',
            field=models.BooleanField(default=False),
        ),
    ]
