# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-28 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0029_order_sameasshipping'),
        ('POS', '0020_auto_20200128_1413'),
    ]

    operations = [
    ]
