# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-30 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0032_productv2_iscod'),
    ]

    operations = [
        migrations.AddField(
            model_name='productv2',
            name='codAdvance',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
