# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-31 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0036_remove_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='couponDiscount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderqtymap',
            name='productName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderqtymap',
            name='sellingPrice',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderqtymap',
            name='shippingPrice',
            field=models.FloatField(default=0),
        ),
    ]
