# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-31 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0038_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqtymap',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='POS.Order'),
        ),
    ]
