# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-31 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0039_orderqtymap_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderqtymap',
            name='productName',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
